#!/usr/bin/env node
/**
 * Bundles src/lektrico-charger-card.js into dist/lektrico-charger-card.js.
 *
 * esbuild resolves `lit` from node_modules, folds in every translation
 * module reached from src/translations/index.js, and minifies — all in one
 * pass, with no configuration file.
 *
 * Version resolution:
 *   LEKTRICO_VERSION env var (set from the git tag by the release workflow),
 *   falling back to "version" in package.json for local and CI builds. The
 *   value is substituted for __VERSION__ in src/const.js, so CARD_VERSION can
 *   never drift from the tag the way a hand-edited constant could.
 *
 * Usage: node scripts/build.mjs
 */

import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";
import * as esbuild from "esbuild";

const ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), "..");

const pkg = JSON.parse(readFileSync(path.join(ROOT, "package.json"), "utf8"));
const version = process.env.LEKTRICO_VERSION || pkg.version;

if (!version) {
  console.error("No version available (LEKTRICO_VERSION unset and package.json has no version).");
  process.exit(1);
}

const entry = path.join(ROOT, "src", "lektrico-charger-card.js");
const outfile = path.join(ROOT, "dist", "lektrico-charger-card.js");

await esbuild.build({
  entryPoints: [entry],
  outfile,
  bundle: true,
  format: "esm",
  target: "es2021",
  minify: true,
  // Emit accented characters as themselves instead of \uXXXX escapes
  // (esbuild defaults to charset: "ascii"). Purely cosmetic — the bundle is
  // loaded as an ES module, which is always decoded as UTF-8 — but it keeps
  // the translations greppable in dist/ and shaves a few hundred bytes.
  charset: "utf8",
  // Keeps Lit's BSD-3 license banner at the end of the bundle, as required
  // when redistributing it.
  legalComments: "eof",
  // The card is a single file by design: dist/ must never contain anything
  // else, because with a release asset attached HACS switches to single-file
  // installs and would stop downloading companion files.
  sourcemap: false,
  define: {
    __VERSION__: JSON.stringify(version),
  },
  banner: {
    js:
      `/*! Lektri.co Charger Card v${version} | GPL-3.0-or-later | https://github.com/naked-head/lektrico-charger-card\n` +
      ` *  Generated by scripts/build.mjs — do not edit this file by hand.\n` +
      ` *  Bundles Lit v${pkg.dependencies.lit} (BSD-3-Clause, see notice at the end of this file). */`,
  },
});

console.log(`Built dist/lektrico-charger-card.js (version ${version})`);